---
# defaults file for openstack-ml2
#

# params to implement ml2 network resource
#
ml2_segmentation_id: "{{ segmentation_id }}"
ml2_segmentation_name: "{{ segmentation_name }}"

# params to implement ml2 port resource
#
ml2_port_name: "{{ port_name }}"
ml2_port_description: "{{ port_description }}"
