---
- name: "eos: get current status of the port"
  eos_command:
    commands:
      - "show interface {{ port }} switchport | json"
      - "show interface {{ port }} | json"
      - "show running-config"
  register: output
  connection: network_cli
  become: True
  become_method: 'enable'

- name: "eos: set port facts"
  set_fact:
    switchport: "{{ output.stdout[0].switchports[port] }}"
    interface: "{{ output.stdout[1].interfaces[port] }}"

- name: "eos: port is configured as routed"
  block:
    - name: "eos: reset interface to defaults"
      eos_config:
        lines: "default interface {{ port }}"

    - name: "eos: build port configuration"
      eos_config:
        lines:
          - "interface {{ port }}"
          - "description {{ port_description }}"
          - "switchport access vlan {{ vlanid }}"
          - "no shutdown"
        parents:
          - "interface {{ port }}"
        running_config: "{{ output.stdout[2] }}"
  when: not switchport.enabled
  connection: network_cli
  become: True
  become_method: 'enable'

- name: "eos: port is configured as switchport"
  block:
    - name: "eos: set the switchport mode to access"
      eos_config:
        lines: "switchport mode access"
        parents: ["interface {{ port }}"]
      when: switchport.switchportInfo.mode != 'access'

    - name: "eos: configure port settings"
      eos_config:
        lines:
          - "description {{ port_description }}"
          - "switchport access vlan {{ vlanid }}"
        parents: ["interface {{ port }}"]
        running_config: "{{ output.stdout[2] }}"

    - name: "eos: administratively enable the port"
      eos_config:
        lines: "no shutdown"
        parents: ["interface {{ port }}"]
      when: interface.interfaceStatus == 'disabled'
  when: switchport.enabled
  connection: network_cli
  become: True
  become_method: 'enable'
