---
# delegate task to localhost to avoid starting the device connection
- name: "check for required fact segmentation_id"
  fail:
    msg: "missing required fact: segmentation_id"
  when: not ml2_segmentation_id
  delegate_to: localhost

# delegate task to localhost to avoid starting the device connection
- name: "check for required fact: segmentation_name"
  fail:
    msg: "missing required fact: segmentation_name"
  when: not ml2_segmentation_name
  delegate_to: localhost

- name: include and run device provider specific tasks
  include_tasks: run.yaml
  vars:
    ml2_resource: create_network
