---
- name: "nxos: get current status of the port"
  nxos_command:
    commands:
      - "show interface {{ port }} switchport | json"
      - "show interface {{ port }} | json"
      - "show running-config"
  register: output

- name: "nxos: set port facts"
  set_fact:
    switchport: "{{ output.stdout[0].TABLE_interface.ROW_interface }}"
    interface: "{{ output.stdout[1].TABLE_interface.ROW_interface }}"

- name: "nxos: port is configured as routed"
  block:
    - name: "nxos: reset interface to defaults"
      nxos_config:
        lines: "default interface {{ port }}"

    - name: "nxos: build port configuration"
      nxos_config:
        lines:
          - "description {{ port_description }}"
          - "switchport"
          - "switchport access vlan {{ vlan_id }}"
          - "no shutdown"
        parents: ["interface {{ port }}"]
        running_config: "{{ output.stdout[2] }}"
  when: switchport.switchport == 'Disabled'

- name: "nxos: port is configured as switchport"
  block:
    - name: "nxos: set the switchport mode to access"
      nxos_config:
        lines: "switchport mode access"
        parents: ["interface {{ port }}"]
      when: switchport.oper_mode != 'access'

    - name: "nxos: configure port settings"
      nxos_config:
        lines:
          - "description {{ port_description }}"
          - "switchport access vlan {{ vlan_id }}"
        parents: ["interface {{ port }}"]
        running_config: "{{ output.stdout[2] }}"

    - name: "nxos: administratively enable the port"
      nxos_config:
        lines: "no shutdown"
        parents: ["interface {{ port }}"]
      when: interface.admin_state == 'down'
  when: switchport.switchport == 'Enabled'
